name: Emscripten Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v14

    - name: Install Raylib Dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential git libsdl2-dev

    - name: Clone Raylib
      run: |
        git clone --branch master https://github.com/raysan5/raylib.git
        cd raylib
        mkdir build
        cd build
        emcmake cmake .. -DPLATFORM=Web -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF
        emmake make
        sudo make install

    - name: Build C Project with Raylib
      run: |
        mkdir build
        cd build
        emcc ../main.c -o main.html -s -I../raylib/src -L../raylib/build/raylib -lraylib -s USE_GLFW=3 -s ASYNCIFY -s GL_ENABLE_GET_PROC_ADDRESS=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s 'EXPORTED_FUNCTIONS=["_main"]'

    - name: Upload compiled files as artifacts
      uses: actions/upload-artifact@v4.6.1
      with:
        name: web-build
        path: build/main.html
